#!/usr/bin/env ruby

lib = File.expand_path("../lib", __FILE__)
p lib
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'expression'

bindings = {}

loop do
  print "calc> "
  input = gets.chomp

  case input
  when "exit"
    puts "Bye bye!"
    exit
  when /^([a-z]+)\s*=\s*(-*\d+)$/
    bindings[$1.to_sym] = $2.to_i
  else
    begin
      puts Expression.new(input).evaluate(bindings)
    rescue StandardError
      puts "Error evaluating RPN expression: #{input.inspect}"
    end
  end
end
